---
- name: Creation du dossier
  file: path=/home/dev/{{ item }} state=directory

- name: Lien vers www
  file: src=/home/dev/{{ item }} dest=/var/www/{{ item }} state=link

- name: Création de la config nginx
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ item }} force=yes
  notify: nginx reload

- name: Activation du domain {{ item }}
  file: src=/etc/nginx/sites-available/{{item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  notify: nginx reload

